name: Generate docs from pod

on:
  push:
    branches:
      - main

jobs:
  generate-doc:
    uses: Omochice/tataku-shared-actions/.github/workflows/generate-doc.yml@8def21b94659ad1e2891bdb7b076f7e1762c23d9 # v2.0.42
    permissions:
      contents: write
      pull-requests: write
    secrets:
      APP_ID: ${{ secrets.PODENO_APP_ID }}
      PRIVATE_KEY: ${{ secrets.PODENO_PRIVATE_KEY }}
